### ISSUE TITLE
which alternatives does this document actually standardize?

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-ae#24]
````
<enrollment-protocol>: MUST reference the protocol being used, which MAY be CMP, CMC, SCEP, EST [[RFC7030](https://github.com/anima-wg/anima-brski-ae/issues/new#RFC7030)] as in BRSKI, or a newly defined approach.
````

I guess that EST RFC7030 already fits exactly into this pattern :-)
Are you proposing to standardize each of CMP, CMC (do we actually need both?), and also SCEP?
SCEP was published after great debate (and a 20 year..! delay).... EST was actually created to replace it, but inertia.

If you want /.well-known/cmc or /.well-known/cmp then IANA Considerations needs to say that.
Or perhaps that work is occuring in LAMPS, in which case we should reference it here.
If there is no present customer demanding SCEP, then we should leave that for future work rather than stir up the SecDir hornets nest.

**Comment by mcr** [comment]
Ah. next section says that CMP end points are created here.
I think that probably the two sections should just be merged, and we don't need to make such broad claims.

**Comment by DDvO** [comment]
Done in version 03.
