### ISSUE TITLE
Fix kramdown warning regarding venue entries "group" and "anima mail"

### ISSUE THREAD

**Issue by DDvO** [anima-wg/anima-brski-ae#26]
Now since the line
```
 venue:
```
is followed by
```
-  group: anima
-  anima mail: {anima@ietf.org}
```
I get
``` 
    *** attributes left {"group"=>"anima", "anima mail"=>{"anima@ietf.org"=>nil}}!
```

**Comment by DDvO** [comment]
It turns out that the above warning is given also when using the `Makefile` of the template by  Martin Thompson: https://github.com/martinthomson/i-d-template.

So I suppose something is wrong with these two lines themselves, or with some related configuration.

**Comment by DDvO** [comment]
It turns out that the above warning is given also when using the `Makefile` of the template by  Martin Thompson: https://github.com/martinthomson/i-d-template.

So I suspect something is wrong with these two lines themselves or with some related configuration.

**Comment by mcr** [comment]
What's your version of kramdown?

I have:

%kdrfc --version
kdrfc, from kramdown-rfc2629 1.6.4

The MT makefiles should install the latest.

Hmm:

*** attributes left {"group"=>"anima", "anima ***@***.***"=>nil}}!

so, maybe I totally did something wrong here.

**Comment by DDvO** [comment]
I have:
```
kdrfc, from kramdown-rfc2629 1.6.17
```
so a newer version than yours.
