### ISSUE TITLE
Clean the repo from generated files (and old version)

### ISSUE THREAD

**Issue by RufusJWB** [anima-wg/anima-brski-ae#30]
I'd propose to do some house cleaning and remove the generated and outdated files from the repo.

**Comment by DDvO** [comment]
I guess you mean the `draft-ietf-anima-brski-a*txt` files?
They are kept as an easy way to have a look at older versions.

**Comment by RufusJWB** [comment]
Mainly I mean the automatically generated *.html, *.pdf, *.xml and *.txt files

**Comment by RufusJWB** [comment]
![image](https://user-images.githubusercontent.com/1633499/207598784-2dc64c79-aead-4c1c-892c-3ebbbbee4d5e.png)

**Comment by RufusJWB** [comment]
so no need for them to be in the repo

**Comment by DDvO** [comment]
I generally agree that it is not good to have auto-generated files in the repo,
but here we keep a copy of the latest generated files for the convenience of those who just want to have a quick look without the need to clone the repo and invoke `make` themselves.
