### ISSUE TITLE
Scope and title (abbreviation) of BRSKI-AE (Shepherd review)

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-ae#34]
Comment received: 

During IETF/IESG review of what became RFC9262, we had a reviewer who did not like the
target name "Traffic Engineering for BIER" (because of ultimately not too shabby arguments),
so we had to have a re-naming contest in the WG and finally renamed it to "Tree Engineering".
Now, when i look at "Alternative Enrollment" protocols and read the text, even this abstract,
then i am thinking that a significant part of the text is about those protocols having to
support authenticate self-contained signed objects. Which does really not become clear
from the title and name "alternative". Alternative for example could also describe 
a protocol which like EST does NOT meet the the requirements that this document
defines as MUST

Proposal from Toerless to rename to "Advantageous Enrollment Protocols in BRSKI" to better underline the advantages of using authenticated self-contained objects for enrollment.

**Comment by DDvO** [comment]
Closing as we agreed that this is fine now.
