### ISSUE TITLE
Discovery description in BRSKI-AE (Shepherd review)

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-ae#35]
Comment summary:

Remove of paragraph 624-629 regarding the discovery optimization in controlled environments requested. It is not seen as necessary as there is already a reference to the discovery document as such and an interim solution is already described in section 5.1. This should be sufficient enough. Providing statements about controlled environments here may rather lead to irritation.

**Comment by DDvO** [comment]
Closing as we agreed that this is fine now.
